default:
	g++ test_infer.cpp -I/opt/ros/kinetic/include -L/opt/ros/kinetic/lib -Wl,-rpath,/opt/ros/kinetic/lib -ltensorflow -lroscpp -lrosconsole -lrostime -lroscpp_serialization -lboost_system -lboost_thread -lpthread -lactionlib -Wall -Wextra 

default1:
	g++ test_infer.cpp -I/opt/ros/kinetic/include -L/opt/ros/kinetic/lib -lroscpp -lrosconsole -lrostime -lroscpp_serialization -lboost_system -lboost_thread -lpthread -lactionlib -Wall -Wextra 
